### PR TITLE
Use functions supported by IE11

### PR DESCRIPTION
**Pull request by saifbechan**
We we were having some problems using this in IE11, and with these changes it is working correctly in all browsers.

### CODE REVIEW

**Comment by kadamwhite** [comment]
@saifbechan Thank you for the PR, and apologies for the delay—this slipped to the backburner while working on Gutenberg tickets! Your change makes sense, I'll test it out and should be able to cut a release by the end of the week.

**Comment by saifbechan** [comment]
@kadamwhite Thanks again. Have you found any issue with my changes?

**Comment by saifbechan** [comment]
@kadamwhite Thanks again. Have you found any issue with my changes? It has been about two weeks now.

**Comment by saifbechan** [comment]
@kadamwhite This issue has been open for nearly a month now, any update on this?

**Pull request merged**
